### ISSUE TITLE
Practice, Qualify, Race, .. do not appear

### ISSUE THREAD

**Issue by Cele91** [jo3stevens/ACServerManager#21] opened 2017-03-24 23:17 UTC
If you select a session, for example Race, but [RACE] does not exist in cfg server, the frame remains white and the panel does not show anything. All white
http://i.xomf.com/bvvvx.png

**Comment by Pringlez** [comment] 2017-03-26 21:16
So if the [RACE] session config is not in the 'server_cfg.ini' file the panel will remain white?

OK I'll look into it when I get some time

**Comment by Cele91** [comment] 2017-03-26 23:17
Yes, same for [BOOKING], [PRACTICE], [QUALIFY], etc

**Comment by jo3stevens** [comment] 2017-03-29 08:56
Hey @Cele91 

I believe this to be another issue caused by the faulty checkboxes. I've just tried reproducing since adding in the switches and everything works fine. Turn a session off and the section is removed from the ini file, turn it back on and fields reappear and the section is added to the ini again.

Can you check with the latest version and let me know if the issue still exists.

Cheers

**Comment by Cele91** [comment] 2017-03-29 09:26
I make some test now and I report soon :)

**Comment by surtic86** [comment] 2017-03-29 09:55
It works on my Linux System.

When you remove a Session it removes it complete form Config and it will show up when you Enable one.

**Comment by jo3stevens** [comment] 2017-03-29 11:39
Good stuff @surtic86 , it's working for me on windows too so will close this off.

**Closed by jo3stevens** 2017-03-29 11:39 UTC

**Comment by Cele91** [comment] 2017-03-29 12:11
All work fine for me :)
